/**
 * Backend RESTful API Interface
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BasicCouponParametri } from './basicCouponParametri';
import { Categoria } from './categoria';
import { Societa } from './societa';

export interface BasicCoupon { 
    descrizione?: string;
    note?: string;
    codice: string;
    tipo: BasicCoupon.TipoEnum;
    importo: number;
    valuta: string;
    sitoWeb?: string;
    scadenza?: string;
    parametri?: Array<BasicCouponParametri>;
    societa: Societa;
    categoria: Categoria;
}
export namespace BasicCoupon {
    export type TipoEnum = 'qrcode' | 'barcode' | 'alfanumerico';
    export const TipoEnum = {
        Qrcode: 'qrcode' as TipoEnum,
        Barcode: 'barcode' as TipoEnum,
        Alfanumerico: 'alfanumerico' as TipoEnum
    };
}