/**
 * Backend RESTful API Interface
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BasicCoupon } from './basicCoupon';
import { BasicCouponParametri } from './basicCouponParametri';
import { Categoria } from './categoria';
import { ObjectId } from './objectId';
import { Societa } from './societa';

export interface Coupon extends BasicCoupon { 
    couponId: ObjectId;
    dataCreazione: string;
}
export namespace Coupon {
}